#!/bin/bash
# install.sh — Install memory-server + nginx on any Ubuntu VPS
#
# Usage:
#   ./install.sh [workspace_dir]
#
# Environment variables (all optional, sensible defaults):
#   WORKSPACE_DIR  — OpenClaw workspace path (default: /root/.openclaw/workspace)
#   PORT           — memory-server port (default: 3001)
#   OPENCLAW_PORT  — OpenClaw gateway port (default: 19789)
#   INSTALL_DIR    — where to install memory-server (default: /opt/memory-server)
#
# What it does:
#   1. Installs nginx (if not present)
#   2. Installs pm2 globally (if not present)
#   3. Copies and installs memory-server
#   4. Configures nginx: /api/memory/* → memory-server, /* → OpenClaw
#   5. Starts memory-server via pm2 with auto-restart on boot
#
# After running this script, update cloudflared to point to http://localhost:80.

set -euo pipefail

WORKSPACE_DIR="${WORKSPACE_DIR:-${1:-/root/.openclaw/workspace}}"
PORT="${PORT:-3001}"
OPENCLAW_PORT="${OPENCLAW_PORT:-19789}"
INSTALL_DIR="${INSTALL_DIR:-/opt/memory-server}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "==> Installing belagent memory-server"
echo "    Workspace:    ${WORKSPACE_DIR}"
echo "    Port:         ${PORT}"
echo "    OpenClaw:     ${OPENCLAW_PORT}"
echo "    Install dir:  ${INSTALL_DIR}"

# ── 1. Install system dependencies ──────────────────────────────

if ! command -v nginx &>/dev/null; then
  echo "==> Installing nginx..."
  apt-get update -qq && apt-get install -y -qq nginx
else
  echo "==> nginx already installed ($(nginx -v 2>&1))"
fi

if ! command -v pm2 &>/dev/null; then
  echo "==> Installing pm2..."
  npm install -g pm2
else
  echo "==> pm2 already installed ($(pm2 -v))"
fi

# ── 2. Install memory-server ────────────────────────────────────

mkdir -p "${INSTALL_DIR}"
cp "${SCRIPT_DIR}/index.js" "${SCRIPT_DIR}/package.json" "${INSTALL_DIR}/"
cd "${INSTALL_DIR}"
npm install --production --silent

# Create .env
cat > "${INSTALL_DIR}/.env" <<EOF
WORKSPACE_DIR=${WORKSPACE_DIR}
PORT=${PORT}
MEMORY_API_TOKEN=
EOF

echo "==> memory-server installed at ${INSTALL_DIR}"

# ── 3. Start with pm2 ──────────────────────────────────────────

pm2 delete memory-server 2>/dev/null || true
pm2 start "${INSTALL_DIR}/index.js" --name memory-server --node-args="--env-file=${INSTALL_DIR}/.env"
pm2 save
pm2 startup -u root --hp /root 2>/dev/null || true

echo "==> memory-server running on port ${PORT}"

# ── 4. Configure nginx ──────────────────────────────────────────

# Generate nginx config with correct ports
cat > /etc/nginx/sites-available/belagent <<NGINX
# belagent nginx config — auto-generated by install.sh
upstream openclaw {
    server 127.0.0.1:${OPENCLAW_PORT};
}

upstream memory_api {
    server 127.0.0.1:${PORT};
}

server {
    listen 80 default_server;
    server_name _;

    location /api/memory/ {
        proxy_pass http://memory_api;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://openclaw;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
NGINX

# Enable site, disable default
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/belagent /etc/nginx/sites-enabled/belagent

nginx -t && systemctl reload nginx

echo "==> nginx configured: /api/memory/* → :${PORT}, /* → :${OPENCLAW_PORT}"

# ── 5. Verify ──────────────────────────────────────────────────

sleep 1
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:${PORT}/api/memory/health" 2>/dev/null || echo "000")
if [ "$HTTP_CODE" = "200" ]; then
  echo "==> Health check passed"
else
  echo "==> Warning: health check returned ${HTTP_CODE} (memory-server may still be starting)"
fi

echo ""
echo "Done. Next steps:"
echo "  1. Update cloudflared to point to http://localhost:80"
echo "  2. Copy the built UI to /usr/lib/node_modules/openclaw/dist/control-ui/"
